---
title: "class06_lab"
format: pdf
editor: visual
author: Hannah Lewack
---

## my first function:)
```{r add}
Add<-function(x,y)
{x+y}
Add(3,7)
Add(x=1, y=100)
Add(c(100,1,100),1)
Add1<-function(x, y=1){x+y}
#add(1,1, z=1). Error in add(1, 1, z = 1) : unused argument (z = 1)
```

write a function that generates a random nucleotide seq of any length

"this is my wee workin snipet"-Barry

```{r generating sequences}
bases<-c("A", "C", "G","T")
#creates randomized sample of 5 bp that will replace it anytime
sequence<- sample(bases, size=5, replace=TRUE)
generate_DNA<-function(length){
  sequence<- sample(bases, size=length, replace=TRUE)
  return(sequence)
}
generate_DNA(5)

bio3d::aa.table
aminoacid<-unique(bio3d::aa.table$aa1)[1:20]

#generate random amino acid sequence
generate_AA<-function(length){
  AA<- sample(aminoacid, size=length, replace=TRUE)
  AA2<-paste(AA, collapse ="")
  return(AA2)
}
generate_AA(4)

#generate random protien sequence of length 6:12
answer<-sapply(6:12, generate_AA)
#make it so you can look it up in blast
cat( paste(">id.", 6:12, "\n", answer, sep=""), sep="\n")
#I get some with 100% alignment but some with none
```

```{r grades}
#load in libraries
library(dplyr)
#example vector to start with
student1 <- c(100, 100, 100, 100, 100, 100, 100, 90)
student2 <- c(100, NA, 90, 90, 90, 90, 97, 80)
student3 <- c(90, NA, NA, NA, NA, NA, NA, NA)

studentgrades<- function(x){
x<-x[order(x, na.last=FALSE)]
x<-x[-1]
x<-mean(x)
return (x)
}
studentgrades(student1)
studentgrades(student2)
studentgrades(student3)
```
