---
title: "Halloweencandy_project"
format: pdf
editor: visual
author: "Hannah Lewack"
---

```{r}
library(ggplot2)
candy_file <- "candy-data.csv"
candy = read.csv(candy_file, row.names=1)
head(candy)
#Q1. How many different candy types are in this dataset?
nrow(candy)
#85
#Q2. How many fruity candy types are in the dataset?
library(dplyr)
candy%>%filter(fruity==1)%>%nrow()
#38
```

```{r}
candy["Twix", ]$winpercent
#Q3. What is your favorite candy in the dataset and what is it’s winpercent value?
unique(candy)
candy%>% filter(rownames(candy)=="Laffy Taffy")%>%select(winpercent)
#laffy taffy, 41.38956
#Q4. What is the winpercent value for “Kit Kat”?
candy%>% filter(rownames(candy)=="Kit Kat")%>%select(winpercent)
#76.76860
#Q5. What is the winpercent value for “Tootsie Roll Snack Bars”?
candy%>% filter(rownames(candy)=="Tootsie Roll Snack Bars")%>%select(winpercent)
#49.65350
library("skimr")
skim(candy)
#Q6. Is there any variable/column that looks to be on a different scale to the majority of the other columns in the dataset?
#winpercent
#Q7. What do you think a zero and one represent for the candy$chocolate column?
#if it is chocolate or if it is not
```

```{r}
#Q8. Plot a histogram of win percent values
hist(candy$winpercent)
ggplot(candy)+aes(winpercent)+geom_histogram(bins=10)+theme_bw()
summary(candy$winpercent)
#Q9. Is the distribution of win percent values symmetrical?
#it is not it starts at 20 but definitely favors the later half
#Q10. Is the center of the distribution above or below 50%?
#it is below 50%
#Q11. On average is chocolate candy higher or lower ranked than fruit candy?
candy
candy%>%filter(chocolate==1)%>%summarize(meanwin=mean(winpercent))
candy%>%filter(fruity==1)%>%summarize(meanwin=mean(winpercent))
#chocolate is higher
#Q12. Is this difference statistically significant?
choc<-candy%>%filter(chocolate==1)
fruit<-candy%>%filter(fruity==1)
?t.test()
t.test(choc$winpercent, fruit$winpercent)
```

```{r}
#Q13. What are the five least liked candy types in this set?
candy %>% arrange(winpercent) %>% head(5)
#Nik L Nip, Boston Baked Beans, Chiclets, Super Bubble, Jawbusters, I prefer the dplyr option because I learned r with dplyr and so it makes the most sense to me
#Q14. What are the top 5 all time favorite candy types out of this set?
candy %>% arrange(desc(winpercent)) %>% head(5)
#Reese's Peanut Butter cup, Reese's Miniatures, Twix, Kit Kat, Snickers

#Q15. Make a first barplot of candy ranking based on winpercent values.
library(ggplot2)
ggplot(candy, aes(x=winpercent, y=rownames(candy))) + geom_col()

ggplot(candy, aes(winpercent, reorder(rownames(candy),winpercent))) + geom_col()

my_cols=rep("black", nrow(candy))
my_cols[as.logical(candy$chocolate)] = "chocolate"
my_cols[as.logical(candy$bar)] = "brown"
my_cols[as.logical(candy$fruity)] = "pink"
my_cols[rownames(candy)=="Laffy Taffy"] = "blue"

ggplot(candy) + 
  aes(winpercent, reorder(rownames(candy),winpercent)) +
  geom_col(fill=my_cols) 
#Q17. What is the worst ranked chocolate candy?
#sixlits
#Q18. What is the best ranked fruity candy?
#starburst
```

```{r}
library(ggrepel)

# How about a plot of price vs win
ggplot(candy) +
  aes(winpercent, pricepercent, label=rownames(candy)) +
  geom_point(col=my_cols) + 
  #removes overlapping text
  geom_text_repel(col=my_cols, size=3.3, max.overlaps = 50)

#Q19. Which candy type is the highest ranked in terms of winpercent for the least money - i.e. offers the most bang for your buck?
#reeces minis
#Q20. What are the top 5 most expensive candy types in the dataset and of these which is the least popular?
candy%>%arrange(pricepercent)
#Hershey's Special Dark, Mr Good Bar, Ring pop, Nik L Nip, Nestle Smarties
#NikLNip
candy%>%arrange(pricepercent)%>%arrange(winpercent)
#Q21. Make a barplot again with geom_col() this time using pricepercent and then improve this step by step, first ordering the x-axis by value and finally making a so called “dot chat” or “lollipop” chart by swapping geom_col() for geom_point() + geom_segment().
ggplot(candy) +
  aes(pricepercent, reorder(rownames(candy), pricepercent)) +
  geom_segment(aes(yend = reorder(rownames(candy), pricepercent), 
                   xend = 0), col="gray40") +
    geom_point()
```

```{r}
library(corrplot)
cij <- cor(candy)
corrplot(cij)
#Q22. Examining this plot what two variables are anti-correlated (i.e. have minus values)?
#chocolate and fruity and bar/pluribus
#Q23. Similarly, what two variables are most positively correlated?
#chocolate and winpercent, also chocolate and bar
```

```{r}
pca <- prcomp(candy, scale=TRUE)
summary(pca)
plot(pca$x[,1:2])
plot(pca$x[,1:2], col=my_cols, pch=16)
# Make a new data-frame with our PCA results and candy data
my_data <- cbind(candy, pca$x[,1:3])
p <- ggplot(my_data) + 
        aes(x=PC1, y=PC2, 
            size=winpercent/100,  
            text=rownames(my_data),
            label=rownames(my_data)) +
        geom_point(col=my_cols)

p
library(ggrepel)

p + geom_text_repel(size=3.3, col=my_cols, max.overlaps = 50)  + 
  theme(legend.position = "none") +
  labs(title="Halloween Candy PCA Space",
       subtitle="Colored by type: chocolate bar (dark brown), chocolate other (light brown), fruity (red), other (black)",
       caption="Data from 538")
#library(plotly)
#ggplotly(p)
par(mar=c(8,4,2,2))
barplot(pca$rotation[,1], las=2, ylab="PC1 Contribution")
#Q24. What original variables are picked up strongly by PC1 in the positive direction? Do these make sense to you?
#fruity, hard, and plurben
```
